DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  customer_id INT NOT NULL,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL
);


DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE STAFF (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  staff_id INT NOT NULL
);

DROP TABLE IF EXISTS CUSTOMER_ORDER;

CREATE TABLE CUSTOMER_ORDER (
  id INT AUTO_INCREMENT PRIMARY KEY,
  order_id INT NOT NULL,
  customer_id INT NOT NULL,
  staff_id INT NOT NULL
);

ALTER TABLE CUSTOMER_ORDER
  ADD FOREIGN KEY (customer_id) REFERENCES CUSTOMER(customer_id);


ALTER TABLE CUSTOMER_ORDER
  ADD FOREIGN KEY (staff_id) REFERENCES STAFF(staff_id);



